### ISSUE TITLE
Feature: Firmware password locking

### ISSUE THREAD

**Issue by Nyami11** [scooterhacking/scooterhacking-issues-public#42]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

Communication

### Priority

low (take your time)

### SHUT Version

0.3.7

### SHFW Version

2.3.2

### Scooter model

Ninebot G30

### Description of the new feature

Right now if a scooter is not connected to a phone, anyone can connect to it without any sort of pairing (on xiaomis at least you have to press the power button to pair), which poses a high risk of a bad actor connecting to it and modifing the settings in a way that it might even cause an accident. It would be great if we could put a password protection to scooters that would lock down firmware flashing, SHFW configuration managing, and scooter locking.

So how would it work? 
I think the best would be if we could set up a password that would be stored on the scooter, and SHUT would store it on the phone to make it more convinient. When we connect to it the scooter, SHUT would check if the scooter is password protected, and there would be some sort of autentication between SHUT and the scooter. Without authenticating, the scooter wouldn't allow the previously mentioned actions. So if it has password protecion, SHUT would ask for the password if it's not stored, and if it is stored, it would autenticate automatically. Third party dashboard apps like ninedash, m365tools should be able to connect the same way as they do now, but since they can't authenticate, the functions that require autentication wouldn't work in them. Storing a password instead of some sort of generated key would be the best option, since those can be remembered relative easily in case someone loses their phone for example.

Problems with it:

- Lock function still resets when someone unplugs the battery, so if someone steals it, they can just unplug-replug it to make it work again.
- A bad actor could still connect to a locked scooter with some un-authenticated application and stay in the bluetooth range, so you wouldn't be able to connect to it and unlock it.
- Biggest downside is obviously that if you forget your password, the only way to reset it is to reflash the firmware using an ST-Link V2.
- If you use a dashboard app, it would be a bit inconvenient, because you would have to disconenct with the dashboard app, then you would have to connect with SHUT just to lock it.
- I'm pretty sure implementing this feature would be pretty hard/time consuming, and there are much more important things to work on right now (like the G2 SHFW support).

### Contact Information

Discord: nyami11

**Comment by paulederbaus** [comment]
@nopbxlr What do you think?

**Comment by nopbxlr** [comment]
I'm not sure. Not only does it require a certain amount of time to put in place, but we would essentially give the users the ability to lock themselves out of their scooter (because inevitably people WILL forget their password/passcode), or by installing SHFW on someone else's scooter, to lock another user from their scooter. This kind of reminds me of the binding restrictions in the Segway app. I think CamiBLE's approach of BLE disabling after 15 seconds of no phone connected makes more sense, but we can't implement that. We have powerusers but we also have more limited ones. I wouldn't take that risk. The safety risk mentionned is not inherent to our modifiction anyways, it's due to the nature of the scooter.

**Comment by Nyami11** [comment]
>  or by installing SHFW on someone else's scooter, to lock another user from their scooter

You can do that already, you can just connect to it and flash a firmware that will brick it.

>  we would essentially give the users the ability to lock themselves out of their scooter

If someone goes on and puts a password on it, he already knows the risks (especially if you make it so SHUT tells them)

I leave my scooter outside every day, and I'm worried that one day someone will just disable my ebrake as a prank or something and by the time I notice it, it will be too late. More and more people gets to know about SHFW each day, so the risk for this to happen with someone is getting bigger. Ofc mitigating this would be easy by just adding a key switch, but still a software solution for stock scooters would be great.

I can't argue with that it would take a lot of time to implement it 👍

**Comment by nopbxlr** [comment]
There would be the possibility that we thought of in the past which is of adding a short passcode to simply change SHFW settings or even see that SHFW is installed at all (in a silent, no ACK manner if the passcode is invalid), but that would not prevent you from going back to another firmware and making that restriction disappear. It would just make it seem like stock firmware. Going as far as restricting a scooter with the above-mentioned issues is unfortunately something that we unanimously disagree on. Since this passcode idea has a different scope than a total lockout and doesn't aim at securing the device, but rather, like most physical locks "keep honest people out" (I hope you see the meaning of this), I will close the issue but keep that one in mind. Feel free to open one up if it ends up being forgotten, or if you wanna improve on the newly defined scope. We also hope to bring something like BLE timeout, or MAC address whitelist someday. Thanks!

**Comment by oadq** [comment]
@nopbxlr 
I think this should be reconsidered.

The issues bxlr and Paul have pointed out can either be solved easily, or are not valid in my opinion.

1. Forgetting the password - same thing with forgetting your phones password, this is the users fault. There are many ways the user can screw something up currently with SHFW, disabling their e-brake, using stupidly high current values. It's impossible to make SHFW idiot proof. Show the user a warning. We shouldn't hold back on useful features just because there's a risk someone will mess it up, this only harms users.
2. Locking the owner out by installing SHFW and setting a password - the same thing can be accomplished already by installing the wrong firmware and bricking the scooter, in both cases, the user will need to flash with ST-Link. I'm not too familiar with BMS firmwares but technically you should be able to install a modified BMS firmware too, which can do some damage as well.

In my opinion the password lock should function in this way:
- we shouldn't try to prevent a "bad person" from unlocking the scooter, this is quite useless, use a physical lock to prevent theft
- instead, lock the SHFW config and firmware updates behind a password
- not locking everything out also solves the issue with dashboard apps, especially on iPhones
- this would not try to prevent stealing, but prevent a malicious actor from changing the SHFW config in a dangerous way silently, which can lead to the scooter owner getting in to an accident, which a physical lock cannot prevent

**Comment by SchattenWolf2008** [comment]
Hey I also like the idea of adding a password feature.

I like the idea of having a mix of both, without the password it acts as normal firmware, and with the password it allows you to access SHFW and change the settings.

I understand the concern of people being able to lock others out, but I could also just connect to someone's scooter and flash bad firmware on it. A password could give me the option to prevent that.

On the other side, a password should not be a mandatory feature, I think its best to give the option to activate or deactivate it if you want, and a warning that informs you about the risk.

I really think a password would be a good feature, and I think the problems mentioned are not really big enough to not give the option at all. Especially as it could also just be a simple four digit password that you can easily remember.

It would be a nice feature to have, thank you for reading this.

**Comment by Z1mmb0** [comment]
This topic never gets old 😁 the devs will hang us for commenting on this refused ticket.

I was not that big of a friend for the password solution, though i understand the concerns. Actually we now have customizable profile switch combinations. Also I remember a discussion about having to press, e.g. the brake, for 10 seconds in order to make the esc flashable.

Based on this there might be new solution paths, like a customizable combination for deactivating and activating the bluetooth module which state is persisted in a last mode. 
Over time the fruits start to hang lower and lower 😁😁

**Comment by dobrishinov** [comment]
I also noticed that the Bluetooth connection is completely open and unprotected, which is a serious security issue. Anyone can connect and change settings, update the firmware, lock, or even brick the scooter.

A great solution would be to automatically disable BLE after a few seconds of inactivity or allow the user to manually toggle it on and off using a specific brake and throttle combination. This would give users better control over Bluetooth access.

I usually ride without my phone connected, and I often forget to turn off the scooter while charging. In these situations, anyone nearby could connect and tamper with the settings. Adding an option to disable BLE or restrict connections would greatly improve security.

I really hope this feature can be implemented. Thanks! ✌️

**Comment by dobrishinov** [comment]
I also noticed that the Bluetooth connection is completely open and unprotected, which is a serious security issue. Anyone can connect and change settings, update the firmware, lock, or even brick the scooter.

A great solution would be to automatically disable BLE after a few seconds of inactivity or allow the user to manually toggle it on and off using a specific brake and throttle combination. This would give users better control over Bluetooth access.

I usually ride without my phone connected, and I often forget to turn off the scooter while charging. In these situations, anyone nearby could connect and tamper with the settings. Adding an option to disable BLE or restrict connections would greatly improve security.

I really hope this feature can be implemented. Thanks! ✌️

**Comment by betamoon1** [comment]
Very interesting topic. I’d like to bring it up again, as I think there is still value in discussing it.

I think oad already made some very good points. Personally, I’d already be happy with a more limited implementation, such as hiding SHFW-related information and configuration behind an optional passcode. The goal wouldn’t be to fully secure the scooter, but simply to prevent casual or unauthorized tampering through SHU.

Regarding the concern of forgetting the password: in my opinion, that is an acceptable risk. SHFW already contains many advanced features that can cause problems if used incorrectly, and users who enable a passcode would do so knowingly. In the worst case, recovery via ST-Link would still be possible.

Another concern that was raised was installing SHFW on someone else’s scooter and locking them out. Unless I’m mistaken, on many newer models SHFW installation already requires physical access and an ST-Link, so this may be less of a concern today than it was when this discussion originally took place.

It would be nice to revive the discussion a little and see whether some form of optional passcode protection for SHFW settings and SHFW visibility could be reconsidered. 😄

**Comment by betamoon1** [comment]
One of the reasons this feature came to mind was a real world situation I experienced recently.

While shopping, I locked my scooter using the 4-digit code feature in SHU. I assumed that, together with the physical lock, this would also prevent unauthorized access through SHU.

Later, I discovered that I could still connect to the scooter without any restrictions from both my iPhone and my Android phone. That made me realize that the lock protects the scooter itself, but not access to SHU functions and configuration.

That’s when I started thinking that an optional passcode for SHFW settings and visibility could be a useful additional layer of protection against unauthorized modifications.

**Comment by SchattenWolf2008** [comment]
Adding my Senf to it, now that ST-Link is required anyway, bad actors couldnt simply just go to a stock scooter and brick flash it or use it to lock out the owner anymore. Instead, everyone who wants to install SHFW is not only required to have a ST-Link, but also has the ability to unbrick or recover the scooter, at home, if they happen to forget their password.

In that sense, maybe it would be worth to consider in the future? It would not only be useful to hide SHFW from strangers, but also protect SHFW users against bad actors. Since with the Install of SHFW, the scooter is also vulnerable to brick flashing again.

The only / main problem I see with this is that a stranger could connect to the scooter of someone who refuses to use a passcode lock, and put one on it. That would require a different solution.

**Comment by betamoon1** [comment]
I think there might be a way to address the concern raised by @SchattenWolf2008.

Instead of simply protecting SHFW with a password, the first device that enables the feature and sets the password could automatically become the trusted device. Whenever this trusted device connects, SHU would automatically unlock all SHFW functionality without asking for the password again.

Any other device could still connect normally, but would first have to enter the password from the three-dot menu (which would always remain visible). Until the correct password is entered, SHFW-related functionality would remain hidden or inaccessible.

For example:

* The Passcode, Deep Sleep, and similar sensitive options would simply not be shown.
* The Config tab could behave exactly like it does on a stock scooter and display something like **"No SHFW detected."**
* The scooter could also spoof stock-looking **BLE, DRV, and BMS** versions so that SHFW is not exposed to unauthorized devices.
* The Flash tab could still remain visible, but flashing would be blocked until the correct password has been entered.

Once authenticated, SHU would immediately reveal the real SHFW information and unlock all protected features.

This would keep everyday use completely seamless for the owner while preventing unauthorized users from discovering or modifying SHFW settings. It would also address the concern that someone could simply connect to another person's scooter and immediately start changing settings or enabling a passcode themselves.

**Comment by lekrsu** [comment]
That would allow a third party to connect, permanently lock and functionally destroy a scooter.

**Comment by betamoon1** [comment]
Maybe the safest compromise would be to make this an optional ST-Link-only setup for X1/X2 users.

Users who want this protection could set the initial SHFW password through ST-Link. After that, SHU would work as described: the trusted device unlocks automatically, while other devices must enter the password before they can access SHFW settings, Tools, Deep Sleep or flashing.

Users who do not want this feature, or do not set a password through ST-Link, would simply keep the current behavior.

This would avoid the risk of a third party connecting to a parked scooter and setting a password through SHU, because the initial password creation would not be possible over Bluetooth.

**Comment by SchattenWolf2008** [comment]
Another idea that just came to my mind:

When doing the ST-Link unlock, if I understand correctly, a modified firmware is installed on the scooter that:
- either has a generic key that ScooterHacking Utility knows and uses to encrypt a firmware before sending it to the scooter
- or completely removes all encryption/decryption for firmware on the scooter's side
to allow ScooterHacking Utility to flash a firmware onto the scooter that it can decrypted, read and installed.

If we do actually just replace the key on a scooter with a generic one, we could instead give the users the option to either use a key that is a mix of the SHU generic key + their own password they chose, or just the normal generic key. This password they can either remember or save somewhere on their computer (just like x3utils does a dump nowadays that you also have to store safely).

By doing this, unauthorized flashing of firmware by third partys could be prevented. I believe this method wouldnt need much modification to SHU or the firmware, but what do I know..

Now with this (or without if the user doesent want it), we could have two SHFW builds:
- SHFW without password protection features
- SHFW with password protection features

So that could give the user the option to prevent others from flashing random firmware on their scooter, and give them the choice to have SHFW with or without password features, which could prevent locking out dilemmas. 


To the password protection itself:

I dont believe it would be nessecary to completely make SHFW stealth just because of a password, since there will most likely be some signs anyway. (Like most people having their last profile active on boot and e.g. showing battery percentage in standby)
Even if someone knows that someone has SHFW installed, I dont really think it will be of any use for them. Instead, if we have a password feature on SHFW, I think it would be enough if it just prevents flashing and changing settings. 

Doing a full stealth when unauthorized feature would probably take a lot of time and ressources aswell.


To the trusted device part:

It is a good idea to make it easier to use, however, I think this shouldnt be a scooter-side thing but rather a SHU-side thing. SHU could remember your password for that scooter and automaticly send it to the scooter when connecting. That would prevent a lot of headache with device recognition from the scooter side, especially considering limited ressources on the Controller.
