### ISSUE TITLE
BUG: External Battery not recognized in Ninebot E series

### ISSUE THREAD

**Issue by lucienne3-web** [scooterhacking/scooterhacking-issues-public#99]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Other

### Severity of issue

high (major functionality broken, no workaround)

### SHUT Version

2.5

### SHFW Version

3.7.2

### Scooter model

Ninebot E20, E25, E45

### Description of the Bug

External battery not recognized in E series . Attached screenshoot of internal and external battery status at the moment !
it is also impossible to up/down grade external battery BMS using SHU utility ( because is not recognized , i think ) 
Test made : Return to OFW 2.7.1 and connected the charger , the external battery start working again !

### Steps to Reproduce

to reproduce the issue simply install SHFW on E45 , starting from earlier 2022 version and update everytime a new update was available . 

### Expected vs. Actual Behavior

have 20 km of autonomy instead of 10

### Contact Information

lucienne3

**Comment by NormalHuman-Anything** [comment]
not me but also heard that from other es4 user i know
somethings gotta be wrong...

**Comment by LarsMde** [comment]
I can confirm the behaviour above (with E22D and external original Accu)

ESC 2.6.11 - BLE 2.1.3 - BMS 1.6.0 - eBMS 2.4.1

After the upgrade, I first fully charged the entire system (A0). On the first ride, after a few kilometres, I noticed that the battery was discharging unusually quickly (when I checked with the ScootBatt, however, it showed that only the internal battery was discharged, the external (original) battery was still at 80%). What was particularly unusual was that the 4 white LEDs on the additional battery were all flashing permanently at the same time. This also happened immediately after switching the entire system off and on again. Otherwise, there were no error messages within the ScootBatt or defective cells.
If I connect the scooter to the charger in this state, it charges both batteries (first the internal one and later, when both are at approximately the same level, the others as well). However, the LED on the charger keeps jumping from red to green, red to green, etc. (the green phase is always slightly longer). (the green phase is always a little longer) and the scooter beeps again and again as if restarting (the front headlight flashes briefly at the same time). After a few minutes this normalises and it charges without flashing, beeping and green phases on the power pack.
I reproduced this behaviour yesterday and today. After the scooter is fully charged, it initially behaves normally when riding. After approx. 1 km, the 4 white LEDs of the additional battery start to flash rhythmically. After travelling approx. 12 km, the battery indicator shows 40%.
It is also noticeable that the ScootBatt app shows me the serial number and status of both batteries, but the firmware of the eBMS is 0.0.0 (I know from a screenshot from 2 days ago that it said 2.4.1). So there seems to be basic communication with the additional battery.

I have now flashed back to 2.7.1 (compat). Now the eBMS is also displayed correctly again (2.4.1) and the scooter is behaving normally (both batteries discharged in parallel - range approx. 40km).

The problem is therefore related to SHFW.

**Comment by lucienne3-web** [comment]
the SHFW versions released last year doesn't have this issue ... why we can't have it ??

**Comment by LarsMde** [comment]
If this is a security feature from the developers' point of view, that the versions are not freely downloadable, then I would first ask that in the future, as with the firmware of DRV, BMS or BLE, at least the selection of the latest version and the version from last year, in which the additional battery still worked, is offered.

Thanks.

**Comment by BastelPichi** [comment]
https://github.com/scooterhacking/scooterhacking-issues-public/issues/93#issuecomment-2181459648
Explains why downgrading is not possible.

SHU/SHFW is only a hobby project and noone gets paid - some other firmwares are paid and not any better (in terms of bugs and support)

**Comment by abdi2342** [comment]
why i cant tuning the xiaomi scooter 4 pro plus
i tried so much  but i cant get it tuning!!!!!

**Comment by IAMFreehandZ** [comment]
> why i cant tuning the xiaomi scooter 4 pro plus
> i tried so much  but i cant get it tuning!!!!!

Not supported

**Comment by LarsMde** [comment]
> [#93 (comment)](https://github.com/scooterhacking/scooterhacking-issues-public/issues/93#issuecomment-2181459648) Explains why downgrading is not possible....

Well, if it is not for security reasons, but only for the compatibility of the tool with the firmware, I would like to ask where I can find the source code of the SHFW firmware so that I can compare last year's with the current one - maybe I can find the error.
In the GIT I find a bunch of binaries of various original firmware, but nothing about SHFW.

**Comment by BastelPichi** [comment]
> > [#93 (comment)](https://github.com/scooterhacking/scooterhacking-issues-public/issues/93#issuecomment-2181459648) Explains why downgrading is not possible....
> 
> Well, if it is not for security reasons, but only for the compatibility of the tool with the firmware, I would like to ask where I can find the source code of the SHFW firmware so that I can compare last year's with the current one - maybe I can find the error. In the GIT I find a bunch of binaries of various original firmware, but nothing about SHFW.

SHFW is not Open Source/Source Open and very, very likely never will.

**Comment by LarsMde** [comment]
Paulederbaus wrote on [comment93](https://github.com/scooterhacking/scooterhacking-issues-public/issues/93#issuecomment-2181459648) "The best way to get rid of them is to help us fix them."

I offer nothing else. Without looking at the source code or parts of it, I cannot help to fix the error.
So I can only hope that the operators of the hobby project will find the error themselves and that I will then donate a few thalers for the great work, because there is a lot of commitment involved.

**Comment by Angelo1976ba** [comment]
Hello, i have the same problem ,battery external Is full charged
I have E22E change region in E45
![Screenshot_20240814-223522~2](https://github.com/user-attachments/assets/b9e8a672-1811-44fd-8ba6-30e46e798615)

**Comment by lucienne3-web** [comment]
What are the chances that this problem will be fixed in the next release? Thanks

**Comment by paulederbaus** [comment]
I contacted you via discord

**Comment by lucienne3-web** [comment]
Ok , flashed pre-release version ! I tested speed , stability , lights , battery charging , all works good ! Problem solved . Thanks to Paul !

**Comment by LarsMde** [comment]
> I contacted you via discord

Sorry, but there is no request on discord.

**Comment by lekrsu** [comment]
> > I contacted you via discord
> 
> Sorry, but there is no request on discord.

It was sent to the creator of the issue report and it's already marked as closed.
